public enum Spr
{
	[SpritePath("Texture2D/Apple_Icon.png")]
	Texture2D_Apple_Icon,
	[SpritePath("Texture2D/Bacon_Icon.png")]
	Texture2D_Bacon_Icon,
	[SpritePath("Texture2D/bakedCarrot.png")]
	Texture2D_bakedCarrot,
	[SpritePath("Texture2D/bakedCheese.png")]
	Texture2D_bakedCheese,
	[SpritePath("Texture2D/bakedChicken.png")]
	Texture2D_bakedChicken,
	[SpritePath("Texture2D/bakedChocolate.png")]
	Texture2D_bakedChocolate,
	[SpritePath("Texture2D/bakedDough.png")]
	Texture2D_bakedDough,
	[SpritePath("Texture2D/bakedEgg.png")]
	Texture2D_bakedEgg,
	[SpritePath("Texture2D/bakedFlour.png")]
	Texture2D_bakedFlour,
	[SpritePath("Texture2D/bakedHoney.png")]
	Texture2D_bakedHoney,
	[SpritePath("Texture2D/bakedPepperoni.png")]
	Texture2D_bakedPepperoni,
	[SpritePath("Texture2D/bakedTomato.png")]
	Texture2D_bakedTomato,
	[SpritePath("Texture2D/Banana_Icon.png")]
	Texture2D_Banana_Icon,
	[SpritePath("Texture2D/Beans_Icon.png")]
	Texture2D_Beans_Icon,
	[SpritePath("Texture2D/BeefJoint_Icon.png")]
	Texture2D_BeefJoint_Icon,
	[SpritePath("Texture2D/Blackberry_Icon.png")]
	Texture2D_Blackberry_Icon,
	[SpritePath("Texture2D/Blender.png")]
	Texture2D_Blender,
	[SpritePath("Texture2D/Blueberry_Icon.png")]
	Texture2D_Blueberry_Icon,
	[SpritePath("Texture2D/BokChoy_Icon.png")]
	Texture2D_BokChoy_Icon,
	[SpritePath("Texture2D/Broccoli_Icon.png")]
	Texture2D_Broccoli_Icon,
	[SpritePath("Texture2D/Bun_Icon.png")]
	Texture2D_Bun_Icon,
	[SpritePath("Texture2D/Burger_CheeseSticks_Drink03.png")]
	Texture2D_Burger_CheeseSticks_Drink03,
	[SpritePath("Texture2D/Burger_Drink01.png")]
	Texture2D_Burger_Drink01,
	[SpritePath("Texture2D/Burger_Fries.png")]
	Texture2D_Burger_Fries,
	[SpritePath("Texture2D/Burger_Fries_CheeseSticks.png")]
	Texture2D_Burger_Fries_CheeseSticks,
	[SpritePath("Texture2D/Burger_Fries_Drink02.png")]
	Texture2D_Burger_Fries_Drink02,
	[SpritePath("Texture2D/Burger_OnionRings.png")]
	Texture2D_Burger_OnionRings,
	[SpritePath("Texture2D/Burger_OnionRings_CheeseSticks.png")]
	Texture2D_Burger_OnionRings_CheeseSticks,
	[SpritePath("Texture2D/Burger_OnionRings_Drink01.png")]
	Texture2D_Burger_OnionRings_Drink01,
	[SpritePath("Texture2D/caketin.png")]
	Texture2D_caketin,
	[SpritePath("Texture2D/Campfire.png")]
	Texture2D_Campfire,
	[SpritePath("Texture2D/Carrot_Icon.png")]
	Texture2D_Carrot_Icon,
	[SpritePath("Texture2D/Cheese_Icon.png")]
	Texture2D_Cheese_Icon,
	[SpritePath("Texture2D/Cherry_Icon.png")]
	Texture2D_Cherry_Icon,
	[SpritePath("Texture2D/Chicken_Icon.png")]
	Texture2D_Chicken_Icon,
	[SpritePath("Texture2D/chocolate_Icon.png")]
	Texture2D_chocolate_Icon,
	[SpritePath("Texture2D/cookedBlueberry.png")]
	Texture2D_cookedBlueberry,
	[SpritePath("Texture2D/cookedChicken.png")]
	Texture2D_cookedChicken,
	[SpritePath("Texture2D/cookedChocolate.png")]
	Texture2D_cookedChocolate,
	[SpritePath("Texture2D/cookedEgg.png")]
	Texture2D_cookedEgg,
	[SpritePath("Texture2D/cookedFish.png")]
	Texture2D_cookedFish,
	[SpritePath("Texture2D/cookedFlour.png")]
	Texture2D_cookedFlour,
	[SpritePath("Texture2D/cookedMeat.png")]
	Texture2D_cookedMeat,
	[SpritePath("Texture2D/cookedMushroom.png")]
	Texture2D_cookedMushroom,
	[SpritePath("Texture2D/cookedPasta.png")]
	Texture2D_cookedPasta,
	[SpritePath("Texture2D/cookedPrawn.png")]
	Texture2D_cookedPrawn,
	[SpritePath("Texture2D/cookedRice.png")]
	Texture2D_cookedRice,
	[SpritePath("Texture2D/cookedStrawberry.png")]
	Texture2D_cookedStrawberry,
	[SpritePath("Texture2D/cookedTomato.png")]
	Texture2D_cookedTomato,
	[SpritePath("Texture2D/Crackers_Icon.png")]
	Texture2D_Crackers_Icon,
	[SpritePath("Texture2D/Cucumber_Icon.png")]
	Texture2D_Cucumber_Icon,
	[SpritePath("Texture2D/cutBlueberry.png")]
	Texture2D_cutBlueberry,
	[SpritePath("Texture2D/cutCarrot.png")]
	Texture2D_cutCarrot,
	[SpritePath("Texture2D/cutCheese.png")]
	Texture2D_cutCheese,
	[SpritePath("Texture2D/cutChicken.png")]
	Texture2D_cutChicken,
	[SpritePath("Texture2D/cutChocolate.png")]
	Texture2D_cutChocolate,
	[SpritePath("Texture2D/cutCucumber.png")]
	Texture2D_cutCucumber,
	[SpritePath("Texture2D/cutDough.png")]
	Texture2D_cutDough,
	[SpritePath("Texture2D/cutFish.png")]
	Texture2D_cutFish,
	[SpritePath("Texture2D/cutHoney.png")]
	Texture2D_cutHoney,
	[SpritePath("Texture2D/cutLettuce.png")]
	Texture2D_cutLettuce,
	[SpritePath("Texture2D/cutMeat.png")]
	Texture2D_cutMeat,
	[SpritePath("Texture2D/cutMushroom.png")]
	Texture2D_cutMushroom,
	[SpritePath("Texture2D/cutPepperoni.png")]
	Texture2D_cutPepperoni,
	[SpritePath("Texture2D/cutPotato.png")]
	Texture2D_cutPotato,
	[SpritePath("Texture2D/cutPrawn.png")]
	Texture2D_cutPrawn,
	[SpritePath("Texture2D/cutStrawberry.png")]
	Texture2D_cutStrawberry,
	[SpritePath("Texture2D/cutTomato.png")]
	Texture2D_cutTomato,
	[SpritePath("Texture2D/C_Burger_CheeseSticks.png")]
	Texture2D_C_Burger_CheeseSticks,
	[SpritePath("Texture2D/C_Burger_CheeseSticks_Drink02.png")]
	Texture2D_C_Burger_CheeseSticks_Drink02,
	[SpritePath("Texture2D/C_Burger_Drink03.png")]
	Texture2D_C_Burger_Drink03,
	[SpritePath("Texture2D/C_Burger_Fries_CheeseSticks.png")]
	Texture2D_C_Burger_Fries_CheeseSticks,
	[SpritePath("Texture2D/C_Burger_Fries_Drink03.png")]
	Texture2D_C_Burger_Fries_Drink03,
	[SpritePath("Texture2D/C_Burger_Fries_OnionRings.png")]
	Texture2D_C_Burger_Fries_OnionRings,
	[SpritePath("Texture2D/C_Burger_OnionRings.png")]
	Texture2D_C_Burger_OnionRings,
	[SpritePath("Texture2D/C_Burger_OnionRings_Drink01.png")]
	Texture2D_C_Burger_OnionRings_Drink01,
	[SpritePath("Texture2D/DeepFatFryer.png")]
	Texture2D_DeepFatFryer,
	[SpritePath("Texture2D/DLC09_BeefJoint_Icon.png")]
	Texture2D_DLC09_BeefJoint_Icon,
	[SpritePath("Texture2D/DLC09_Broccoli_Icon.png")]
	Texture2D_DLC09_Broccoli_Icon,
	[SpritePath("Texture2D/DLC09_DriedFruit_Icon.png")]
	Texture2D_DLC09_DriedFruit_Icon,
	[SpritePath("Texture2D/DLC09_Milk_Icon.png")]
	Texture2D_DLC09_Milk_Icon,
	[SpritePath("Texture2D/DLC09_Orange_Icon.png")]
	Texture2D_DLC09_Orange_Icon,
	[SpritePath("Texture2D/DLC09_SplitPan.png")]
	Texture2D_DLC09_SplitPan,
	[SpritePath("Texture2D/DLC09_Strawberry_Icon.png")]
	Texture2D_DLC09_Strawberry_Icon,
	[SpritePath("Texture2D/DLC09_WhippedCream_Icon.png")]
	Texture2D_DLC09_WhippedCream_Icon,
	[SpritePath("Texture2D/DLC09_WholeChicken_Icon.png")]
	Texture2D_DLC09_WholeChicken_Icon,
	[SpritePath("Texture2D/DLC13_Melon_Icon.png")]
	Texture2D_DLC13_Melon_Icon,
	[SpritePath("Texture2D/DLC13_Strawberry_Icon.png")]
	Texture2D_DLC13_Strawberry_Icon,
	[SpritePath("Texture2D/DLC13_UI_MooncakeChocolate.png")]
	Texture2D_DLC13_UI_MooncakeChocolate,
	[SpritePath("Texture2D/DLC13_UI_MooncakeStrawberry.png")]
	Texture2D_DLC13_UI_MooncakeStrawberry,
	[SpritePath("Texture2D/DLC13_UI_MooncakeStrawberryChocolate.png")]
	Texture2D_DLC13_UI_MooncakeStrawberryChocolate,
	[SpritePath("Texture2D/DLC13_UI_MooncakeWatermelon.png")]
	Texture2D_DLC13_UI_MooncakeWatermelon,
	[SpritePath("Texture2D/Donut_Choco.png")]
	Texture2D_Donut_Choco,
	[SpritePath("Texture2D/Donut_Plain.png")]
	Texture2D_Donut_Plain,
	[SpritePath("Texture2D/Donut_Raspberry.png")]
	Texture2D_Donut_Raspberry,
	[SpritePath("Texture2D/Dough_Icon.png")]
	Texture2D_Dough_Icon,
	[SpritePath("Texture2D/DriedFruit_Icon.png")]
	Texture2D_DriedFruit_Icon,
	[SpritePath("Texture2D/Drink01_Icon.png")]
	Texture2D_Drink01_Icon,
	[SpritePath("Texture2D/Drink02_Icon.png")]
	Texture2D_Drink02_Icon,
	[SpritePath("Texture2D/Drink03_Icon.png")]
	Texture2D_Drink03_Icon,
	[SpritePath("Texture2D/egg_Icon.png")]
	Texture2D_egg_Icon,
	[SpritePath("Texture2D/Fish_Icon.png")]
	Texture2D_Fish_Icon,
	[SpritePath("Texture2D/Flour_Icon.png")]
	Texture2D_Flour_Icon,
	[SpritePath("Texture2D/friedChicken.png")]
	Texture2D_friedChicken,
	[SpritePath("Texture2D/friedPotato.png")]
	Texture2D_friedPotato,
	[SpritePath("Texture2D/FryingPan.png")]
	Texture2D_FryingPan,
	[SpritePath("Texture2D/Grapes_Icon.png")]
	Texture2D_Grapes_Icon,
	[SpritePath("Texture2D/Grill_Icon.png")]
	Texture2D_Grill_Icon,
	[SpritePath("Texture2D/honeycomb_Icon.png")]
	Texture2D_honeycomb_Icon,
	[SpritePath("Texture2D/HotdogBun_Icon.png")]
	Texture2D_HotdogBun_Icon,
	[SpritePath("Texture2D/Hotdog_Ketchup.png")]
	Texture2D_Hotdog_Ketchup,
	[SpritePath("Texture2D/Hotdog_KetchupMustard.png")]
	Texture2D_Hotdog_KetchupMustard,
	[SpritePath("Texture2D/Hotdog_Mustard.png")]
	Texture2D_Hotdog_Mustard,
	[SpritePath("Texture2D/Hotdog_Onions.png")]
	Texture2D_Hotdog_Onions,
	[SpritePath("Texture2D/Hotdog_OnionsKetchup.png")]
	Texture2D_Hotdog_OnionsKetchup,
	[SpritePath("Texture2D/Hotdog_OnionsMustard.png")]
	Texture2D_Hotdog_OnionsMustard,
	[SpritePath("Texture2D/Hotdog_Plain.png")]
	Texture2D_Hotdog_Plain,
	[SpritePath("Texture2D/Ketchup_Icon.png")]
	Texture2D_Ketchup_Icon,
	[SpritePath("Texture2D/Leek_Icon.png")]
	Texture2D_Leek_Icon,
	[SpritePath("Texture2D/Lettuce_Icon.png")]
	Texture2D_Lettuce_Icon,
	[SpritePath("Texture2D/Marshmallow_Icon.png")]
	Texture2D_Marshmallow_Icon,
	[SpritePath("Texture2D/Meat_Icon.png")]
	Texture2D_Meat_Icon,
	[SpritePath("Texture2D/Melon_Icon.png")]
	Texture2D_Melon_Icon,
	[SpritePath("Texture2D/Milk_Icon.png")]
	Texture2D_Milk_Icon,
	[SpritePath("Texture2D/mixedBlueberry.png")]
	Texture2D_mixedBlueberry,
	[SpritePath("Texture2D/mixedCarrot.png")]
	Texture2D_mixedCarrot,
	[SpritePath("Texture2D/mixedChocolate.png")]
	Texture2D_mixedChocolate,
	[SpritePath("Texture2D/mixedEgg.png")]
	Texture2D_mixedEgg,
	[SpritePath("Texture2D/mixedFlour.png")]
	Texture2D_mixedFlour,
	[SpritePath("Texture2D/mixedHoney.png")]
	Texture2D_mixedHoney,
	[SpritePath("Texture2D/mixedMeat.png")]
	Texture2D_mixedMeat,
	[SpritePath("Texture2D/mixedPrawn.png")]
	Texture2D_mixedPrawn,
	[SpritePath("Texture2D/mixedStrawberry.png")]
	Texture2D_mixedStrawberry,
	[SpritePath("Texture2D/Mixer.png")]
	Texture2D_Mixer,
	[SpritePath("Texture2D/Mushroom_Icon.png")]
	Texture2D_Mushroom_Icon,
	[SpritePath("Texture2D/Mustard_Icon.png")]
	Texture2D_Mustard_Icon,
	[SpritePath("Texture2D/Noodle_Icon.png")]
	Texture2D_Noodle_Icon,
	[SpritePath("Texture2D/Olive_Icon.png")]
	Texture2D_Olive_Icon,
	[SpritePath("Texture2D/Onion_Icon.png")]
	Texture2D_Onion_Icon,
	[SpritePath("Texture2D/Orange_Icon.png")]
	Texture2D_Orange_Icon,
	[SpritePath("Texture2D/OvenPot.png")]
	Texture2D_OvenPot,
	[SpritePath("Texture2D/pasta_Icon.png")]
	Texture2D_pasta_Icon,
	[SpritePath("Texture2D/Peach_Icon.png")]
	Texture2D_Peach_Icon,
	[SpritePath("Texture2D/Pepperoni_Icon.png")]
	Texture2D_Pepperoni_Icon,
	[SpritePath("Texture2D/Pineapple_Icon.png")]
	Texture2D_Pineapple_Icon,
	[SpritePath("Texture2D/Pot.png")]
	Texture2D_Pot,
	[SpritePath("Texture2D/Potato_Icon.png")]
	Texture2D_Potato_Icon,
	[SpritePath("Texture2D/prawn_Icon.png")]
	Texture2D_prawn_Icon,
	[SpritePath("Texture2D/Raspberry_Icon.png")]
	Texture2D_Raspberry_Icon,
	[SpritePath("Texture2D/Rice_Icon.png")]
	Texture2D_Rice_Icon,
	[SpritePath("Texture2D/Sausage_Icon.png")]
	Texture2D_Sausage_Icon,
	[SpritePath("Texture2D/Seaweed_Icon.png")]
	Texture2D_Seaweed_Icon,
	[SpritePath("Texture2D/SplitPan.png")]
	Texture2D_SplitPan,
	[SpritePath("Texture2D/steamedCarrot.png")]
	Texture2D_steamedCarrot,
	[SpritePath("Texture2D/steamedFish.png")]
	Texture2D_steamedFish,
	[SpritePath("Texture2D/steamedFlour.png")]
	Texture2D_steamedFlour,
	[SpritePath("Texture2D/steamedMeat.png")]
	Texture2D_steamedMeat,
	[SpritePath("Texture2D/steamedPrawn.png")]
	Texture2D_steamedPrawn,
	[SpritePath("Texture2D/Steamer.png")]
	Texture2D_Steamer,
	[SpritePath("Texture2D/Strawberry_Icon.png")]
	Texture2D_Strawberry_Icon,
	[SpritePath("Texture2D/Tomato_Icon.png")]
	Texture2D_Tomato_Icon,
	[SpritePath("Texture2D/Tortilla_Icon.png")]
	Texture2D_Tortilla_Icon,
	[SpritePath("Texture2D/t_icon_carrot_dumpling_d.png")]
	Texture2D_t_icon_carrot_dumpling_d,
	[SpritePath("Texture2D/t_icon_chicken_nuggets_chips_d.png")]
	Texture2D_t_icon_chicken_nuggets_chips_d,
	[SpritePath("Texture2D/t_icon_chicken_nuggets_d.png")]
	Texture2D_t_icon_chicken_nuggets_d,
	[SpritePath("Texture2D/t_icon_chips_d.png")]
	Texture2D_t_icon_chips_d,
	[SpritePath("Texture2D/ui_Breakfast_BaconEggSausageBeans_01.png")]
	Texture2D_ui_Breakfast_BaconEggSausageBeans_01,
	[SpritePath("Texture2D/ui_Breakfast_BaconEggSausage_01.png")]
	Texture2D_ui_Breakfast_BaconEggSausage_01,
	[SpritePath("Texture2D/ui_Breakfast_BaconEgg_01.png")]
	Texture2D_ui_Breakfast_BaconEgg_01,
	[SpritePath("Texture2D/ui_Breakfast_SausageBeans_01.png")]
	Texture2D_ui_Breakfast_SausageBeans_01,
	[SpritePath("Texture2D/ui_Breakfast_SausageEggBeans_01.png")]
	Texture2D_ui_Breakfast_SausageEggBeans_01,
	[SpritePath("Texture2D/ui_CakePlain_01.png")]
	Texture2D_ui_CakePlain_01,
	[SpritePath("Texture2D/ui_CarrotCake_01.png")]
	Texture2D_ui_CarrotCake_01,
	[SpritePath("Texture2D/ui_cheeseandtomatopizza.png")]
	Texture2D_ui_cheeseandtomatopizza,
	[SpritePath("Texture2D/ui_cheeseburgerlettucetomato_01.png")]
	Texture2D_ui_cheeseburgerlettucetomato_01,
	[SpritePath("Texture2D/ui_cheeseburgerlettuce_01.png")]
	Texture2D_ui_cheeseburgerlettuce_01,
	[SpritePath("Texture2D/ui_cheeseburger_01.png")]
	Texture2D_ui_cheeseburger_01,
	[SpritePath("Texture2D/ui_chickenburrito.png")]
	Texture2D_ui_chickenburrito,
	[SpritePath("Texture2D/ui_chickenpizza.png")]
	Texture2D_ui_chickenpizza,
	[SpritePath("Texture2D/ui_ChocolateCake_01.png")]
	Texture2D_ui_ChocolateCake_01,
	[SpritePath("Texture2D/ui_ChrismasPuddingOrange_01.png")]
	Texture2D_ui_ChrismasPuddingOrange_01,
	[SpritePath("Texture2D/ui_ChrismasPudding_01.png")]
	Texture2D_ui_ChrismasPudding_01,
	[SpritePath("Texture2D/ui_CucumberSushi_01.png")]
	Texture2D_ui_CucumberSushi_01,
	[SpritePath("Texture2D/ui_FishandCucumberSushi.png")]
	Texture2D_ui_FishandCucumberSushi,
	[SpritePath("Texture2D/ui_FishSushi.png")]
	Texture2D_ui_FishSushi,
	[SpritePath("Texture2D/ui_FishSushimi.png")]
	Texture2D_ui_FishSushimi,
	[SpritePath("Texture2D/UI_FruitPlatterGrapesOrange_01.png")]
	Texture2D_UI_FruitPlatterGrapesOrange_01,
	[SpritePath("Texture2D/UI_FruitPlatterPeachGrapesOrange_01.png")]
	Texture2D_UI_FruitPlatterPeachGrapesOrange_01,
	[SpritePath("Texture2D/UI_FruitPlatterPeachGrapes_01.png")]
	Texture2D_UI_FruitPlatterPeachGrapes_01,
	[SpritePath("Texture2D/UI_FruitPlatterPeachOrange_01.png")]
	Texture2D_UI_FruitPlatterPeachOrange_01,
	[SpritePath("Texture2D/ui_Hawaiianburger_01.png")]
	Texture2D_ui_Hawaiianburger_01,
	[SpritePath("Texture2D/ui_HotChocolateWithCreamMallows_01.png")]
	Texture2D_ui_HotChocolateWithCreamMallows_01,
	[SpritePath("Texture2D/ui_HotChocolateWithCream_01.png")]
	Texture2D_ui_HotChocolateWithCream_01,
	[SpritePath("Texture2D/ui_HotChocolateWithMallows_01.png")]
	Texture2D_ui_HotChocolateWithMallows_01,
	[SpritePath("Texture2D/ui_HotChocolate_01.png")]
	Texture2D_ui_HotChocolate_01,
	[SpritePath("Texture2D/UI_HotPotDoubleMeat_01.png")]
	Texture2D_UI_HotPotDoubleMeat_01,
	[SpritePath("Texture2D/UI_HotPotDoublePrawn_01.png")]
	Texture2D_UI_HotPotDoublePrawn_01,
	[SpritePath("Texture2D/UI_HotPotMeat_01.png")]
	Texture2D_UI_HotPotMeat_01,
	[SpritePath("Texture2D/UI_HotPotPrawn_01.png")]
	Texture2D_UI_HotPotPrawn_01,
	[SpritePath("Texture2D/ui_KebabChickenTomatoMeat_01.png")]
	Texture2D_ui_KebabChickenTomatoMeat_01,
	[SpritePath("Texture2D/ui_KebabChickenTomato_01.png")]
	Texture2D_ui_KebabChickenTomato_01,
	[SpritePath("Texture2D/ui_KebabMushroomPineappleMeatl_01.png")]
	Texture2D_ui_KebabMushroomPineappleMeatl_01,
	[SpritePath("Texture2D/ui_KebabMushroomPineappleTomato_01.png")]
	Texture2D_ui_KebabMushroomPineappleTomato_01,
	[SpritePath("Texture2D/ui_lettucesalad_01.png")]
	Texture2D_ui_lettucesalad_01,
	[SpritePath("Texture2D/ui_lettucetomatocucumbersalad_01.png")]
	Texture2D_ui_lettucetomatocucumbersalad_01,
	[SpritePath("Texture2D/ui_lettucetomatosalad_01.png")]
	Texture2D_ui_lettucetomatosalad_01,
	[SpritePath("Texture2D/ui_meatburrito.png")]
	Texture2D_ui_meatburrito,
	[SpritePath("Texture2D/ui_MeatDumpling_01.png")]
	Texture2D_ui_MeatDumpling_01,
	[SpritePath("Texture2D/ui_mushroomburrito.png")]
	Texture2D_ui_mushroomburrito,
	[SpritePath("Texture2D/ui_PancakeChocolate_01.png")]
	Texture2D_ui_PancakeChocolate_01,
	[SpritePath("Texture2D/ui_Pancake_01.png")]
	Texture2D_ui_Pancake_01,
	[SpritePath("Texture2D/ui_Pancake_Blueberry_01.png")]
	Texture2D_ui_Pancake_Blueberry_01,
	[SpritePath("Texture2D/ui_pastameat_01.png")]
	Texture2D_ui_pastameat_01,
	[SpritePath("Texture2D/ui_pastamushroom_01.png")]
	Texture2D_ui_pastamushroom_01,
	[SpritePath("Texture2D/ui_pastaseafood_01.png")]
	Texture2D_ui_pastaseafood_01,
	[SpritePath("Texture2D/ui_pastatomato_01.png")]
	Texture2D_ui_pastatomato_01,
	[SpritePath("Texture2D/ui_pepperonipizza.png")]
	Texture2D_ui_pepperonipizza,
	[SpritePath("Texture2D/ui_pie_apple_01.png")]
	Texture2D_ui_pie_apple_01,
	[SpritePath("Texture2D/ui_pie_apple_blackberry_01.png")]
	Texture2D_ui_pie_apple_blackberry_01,
	[SpritePath("Texture2D/ui_pie_apple_cherry_01.png")]
	Texture2D_ui_pie_apple_cherry_01,
	[SpritePath("Texture2D/ui_pie_blackberry_01.png")]
	Texture2D_ui_pie_blackberry_01,
	[SpritePath("Texture2D/ui_pie_cherry_01.png")]
	Texture2D_ui_pie_cherry_01,
	[SpritePath("Texture2D/ui_Pizza_BlackOlive_01.png")]
	Texture2D_ui_Pizza_BlackOlive_01,
	[SpritePath("Texture2D/ui_plainburger_01.png")]
	Texture2D_ui_plainburger_01,
	[SpritePath("Texture2D/ui_PrawnDumpling_01.png")]
	Texture2D_ui_PrawnDumpling_01,
	[SpritePath("Texture2D/ui_PrawnSushimi.png")]
	Texture2D_ui_PrawnSushimi,
	[SpritePath("Texture2D/ui_roast_beef_potato_carrot_01.png")]
	Texture2D_ui_roast_beef_potato_carrot_01,
	[SpritePath("Texture2D/ui_roast_beef_potato_carrot_broccoli_01.png")]
	Texture2D_ui_roast_beef_potato_carrot_broccoli_01,
	[SpritePath("Texture2D/ui_roast_chicken_potato_carrot_01.png")]
	Texture2D_ui_roast_chicken_potato_carrot_01,
	[SpritePath("Texture2D/ui_roast_chicken_potato_carrot_broccoli_01.png")]
	Texture2D_ui_roast_chicken_potato_carrot_broccoli_01,
	[SpritePath("Texture2D/ui_SmoothieAll_01.png")]
	Texture2D_ui_SmoothieAll_01,
	[SpritePath("Texture2D/ui_Smoothie_bananaPineapple_01.png")]
	Texture2D_ui_Smoothie_bananaPineapple_01,
	[SpritePath("Texture2D/ui_Smoothie_Banana_01.png")]
	Texture2D_ui_Smoothie_Banana_01,
	[SpritePath("Texture2D/ui_Smoothie_Melon_01.png")]
	Texture2D_ui_Smoothie_Melon_01,
	[SpritePath("Texture2D/ui_Smoothie_Strawberry_01.png")]
	Texture2D_ui_Smoothie_Strawberry_01,
	[SpritePath("Texture2D/ui_Smore_Banana_01.png")]
	Texture2D_ui_Smore_Banana_01,
	[SpritePath("Texture2D/ui_Smore_Chocolate_01.png")]
	Texture2D_ui_Smore_Chocolate_01,
	[SpritePath("Texture2D/ui_Smore_Plain_01.png")]
	Texture2D_ui_Smore_Plain_01,
	[SpritePath("Texture2D/ui_Smore_StrawberryBanana_01.png")]
	Texture2D_ui_Smore_StrawberryBanana_01,
	[SpritePath("Texture2D/ui_Smore_Strawberry_01.png")]
	Texture2D_ui_Smore_Strawberry_01,
	[SpritePath("Texture2D/ui_soup_broccoli_cheese_01.png")]
	Texture2D_ui_soup_broccoli_cheese_01,
	[SpritePath("Texture2D/ui_soup_carrot_potato_01.png")]
	Texture2D_ui_soup_carrot_potato_01,
	[SpritePath("Texture2D/ui_soup_leek_potato_01.png")]
	Texture2D_ui_soup_leek_potato_01,
	[SpritePath("Texture2D/ui_SteamedFish_01.png")]
	Texture2D_ui_SteamedFish_01,
	[SpritePath("Texture2D/ui_StrawberryPancake_01.png")]
	Texture2D_ui_StrawberryPancake_01,
	[SpritePath("Texture2D/WhippedCream_Icon.png")]
	Texture2D_WhippedCream_Icon,
	[SpritePath("Texture2D/WholeChicken_Icon.png")]
	Texture2D_WholeChicken_Icon,
}
